### ISSUE TITLE
No way to running this app......

### ISSUE THREAD

**Issue by JingHai-Lingyun** [alazeprt/MCServerDownload-GUI#2]
just look the title :)

**Comment by g1thubhack3r** [comment]
Please view [the introduction](https://githubfast.com/alazeprt/MCServerDownload-GUI#introduction).
After installing Java SE 18, go to the directory of this app and run `java -jar MCServerDownload-GUI.jar`

**Comment by JingHai-Lingyun** [comment]
oh my god it need JavaSE 18
i only have Jdk17 :(
thanks for help

**Comment by g1thubhack3r** [comment]
no problem
I think it will be better if you close this issue as "won't fix" because it is invalid.

**Comment by JingHai-Lingyun** [comment]
good idea
